# Author by chanhihi
# Date 2023.08.09
# name-template: "v$NEXT_MINOR_VERSION 🦊"
# tag-template: "v$NEXT_MINOR_VERSION"

name-template: "v$RESOLVED_VERSION 🦊"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - "⚠️ Breaking changes"
  minor:
    labels:
      - "✨ Enhancement"
  patch:
    labels:
      - "⚒ Refactor"
      - "🐞 Bug"
  default: patch

categories:
  - title: "⚠️ Breaking changes"
    labels:
      - "⚠️ Breaking Change"
  - title: "🚀 Features"
    labels:
      - "✨ Enhancement"
      - "⚒ Refactor"
      - "🏛 Structure"
  - title: "🐛 Bug Fixes"
    labels:
      - "🐞 Bug"
  - title: "📚 Documentation"
    labels:
      - "📄 Documentation"
  - title: "🎨 Style"
    labels:
      - "💄 UI/UX"
  - title: "🏗 Infrastructure"
    labels:
      - "🌐 DevOps"
exclude-labels:
  - "💖 Question"
  - "☂️ Umbrella"

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'

template: |
  ## Changes
  $CHANGES
