# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Constants
APP_NAME = "iBox"
SCHEME = "iBox"
BUNDLE_ID = "com.box42.iBox"

KEYCHAIN_NAME = ENV["KEYCHAIN_NAME"]
KEYCHAIN_PASSWORD = ENV["KEYCHAIN_PASSWORD"]

default_platform(:ios)

platform :ios do
  # Keychain
  desc "Save To Keychain"
  lane :set_keychain do |options|
    create_keychain(
      name: "#{KEYCHAIN_NAME}",
      password: "#{KEYCHAIN_PASSWORD}",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    import_certificate(
      certificate_path: "Tuist/Signing/release.cer",
      keychain_name: "#{KEYCHAIN_NAME}",
      keychain_password: "#{KEYCHAIN_PASSWORD}"
    )

    import_certificate(
      certificate_path: "Tuist/Signing/release.p12",
      keychain_name: "#{KEYCHAIN_NAME}",
      keychain_password: "#{KEYCHAIN_PASSWORD}"
    )

    install_provisioning_profile(path: "Tuist/Signing/#{APP_NAME}.Release.mobileprovision")
  end

  # Upload TestFlight
  desc "Push to TestFlight"
  lane :tf do |options|
    # AppStore Connect API key
    app_store_connect_api_key(is_key_content_base64: true, in_house: false)

    # BuildNumber Up
    increment_build_number({ build_number: latest_testflight_build_number() + 1 })

    # Build App
    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{SCHEME}",
      export_method: "app-store"
    )

    # Upload to TestFlight
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
